MinutesConversion.class: MinutesConversion.java
	javac MinutesConversion.java

BurmaShave.class:
	javac BurmaShave.java

MilesConversion.class: MilesConversion.java
	javac MilesConversion.java

MilesConversionInteractive.class: MilesConversionInteractive.java
	javac MilesConversionInteractive.java

clean:
	rm *.class
	rm *~
