TestLease.class: TestLease.java
	javac TestLease.java

Lease.class: Lease.java
	javac Lease.java

FormLetterWriter.class: FormLetterWriter.java
	javac FormLetterWriter.java

NumbersDemo.class: NumbersDemo.java
	javac NumbersDemo.java

clean:
	rm *.class
	rm *~
