TestApartments.class: Apartment.java TestApartments.java
	javac Apartment.java
	javac TestApartments.java

Apartment.class: Apartment.java
	javac Apartment.java

AscendingAndDescending.class: AscendingAndDescending.java
	javac AscendingAndDescending.java

clean:
	rm *.class
	rm *~
